title: Tanner Gooding's Blog
description: >-
  Blogging about .NET, Numerics, Hardware Intrinsics, and more.

author: Tanner Gooding
email: tagoo@outlook.com

url: "https://blog.tagoo.dev"
baseurl: ""

google_analytics: UA-135469787-1
show_excerpts: false

disqus:
  shortname: blog-tagoo-dev

minima:
  date_format: "%-d %b %Y"

  social_links:
    github:  tannergooding
    twitter: tannergooding
    rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
